# Generated by Django 5.2 on 2026-01-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_placeorder_user_id_alter_placeorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeorder',
            name='address',
            field=models.CharField(default='Not Provided', max_length=255),
        ),
        migrations.AddField(
            model_name='placeorder',
            name='payment_method',
            field=models.CharField(default='Not Provided', max_length=50),
        ),
    ]
